Milestone2- TheNewsweek
Anvi98/Project-3-Newsweek pull request #6
Opened 2021-03-03 18:03 UTC by Anvi98

In this second milestone, we created the 3 columns main section of the website for the 3 screen sizes.

Column 1 (Featured stories Sponsored insights / Rankings)

Column 2 (Top story My turn Culture & travel More stories Latest news)

Column 3 (The debate Opinion Sponsored insights / Rankings Free signup)

2021-03-03 19:37 UTC, smcommits requested changes
# Status: Changes Required

### Hello, team! You have done a great job. Your website looks fairly similar to the original. But, we still need to make a few adjustments to get this PR approved. 

## Required Changes

- [x] **The column layout on each screen should match the original.** 
At medium screen size, the layout on the original website uses two columns followed by one full-width column. Your website is using 3 column layout for the entire webpage. Please fix this. Refer to the images below

### Original website on medium screen size. 
![originalTabCol](https://user-images.githubusercontent.com/59168430/109860422-24365580-7c84-11eb-885a-31c2799ffcc3.png)

### Your website on medium screen size. 
![createdy](https://user-images.githubusercontent.com/59168430/109860605-6069b600-7c84-11eb-8d34-9da88bc49da5.png)

- [ ] **The order of sections on every screen size should match with the original** 
The sections should have the following order on small screen size or mobile view. 
![order](https://user-images.githubusercontent.com/59168430/109861078-eb4ab080-7c84-11eb-95b6-9d53c5d9fe77.png)

In mobile view, the sections on your website don't follow the same order. For instance, the "Featured Stories" section appears first, while on the original the "top stories" section is appearing first.

# 
Please implement the changes and request another review from your dashboard.
### If you need any help or if you think I failed to notice something and have made an unreasonable request, please don't hesitate to reach out to me on [slack](https://microverse-students.slack.com/team/U017N7LLZ40)

2021-03-04 19:54 UTC, BrianSammit requested changes
CHANGES REQUIRED ♻️ 🔴 
-------
Hello @Anvi98 @errea 👋 you are doing a great job on this milestone 👏 💪 
There are a few changes to make to full fit this project 🛠️ see them below 👀 👇 
-----------------

- [ ] Improve your commit messages. You have minor errors in the formatting rules for good commit messages.  Remember the messages must be in the imperative.  [Here](https://github.com/trein/dev-best-practices/wiki/Git-Commit-Best-Practices#formatting-rules) you can read about the formatting rules. [Here](https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message) you can read how to change a commit message. You don't need to change this minor error this time but keep these formatting rules in mind for the next commits. 
 ## On Desktop
- [ ]You are missing the "SPONSORED INSIGHT" section on the first column. 
- [ ] You are missing the sections "CULTURE & TRAVEL" and "MY TURN" on the second column. 

## On Tablet

- [ ] You are missing the "SPONSORED INSIGHT" section on the first column. 
- [ ] You are missing the sections "CULTURE & TRAVEL" and "MY TURN" on the second column. 
- [ ] The "THE DEBATE" and "OPINION" sections must be with full with of the page. kindly fix it. 
- [ ] The "SPONSORED INSIGHT" and "FREE SIGN UP" must be centered. 

## On Mobile

- [ ] You are repeating "TOP STORY", "MY TURN", "CULTURE AND TRAVEL", "MORE STORIES", "LATEST NEWS", "THE DEBATE", "OPINION", "SPONSORED INSIGHT" AND "FREE SIGN UP".

## GENERAL

- [ ] Every piece of news. 
    - The image must be a link `a` tag. please add it. E.g `<a href="#"><img src="img/mid1.webp" class="articles" alt=""></a>`
    - The title must be a link `a` tag. please add it. E.g `<h3 class="mid-title"><a href="#">The 73 People Pardoned by Donald Trump on His Last Day As President</a></h3>`

- [ ] Improve your README. In the section "Steps to follow" write a step-by-step about how to clone your repository. Remember not everyone is a programmer. E.g "what command to use, where to write the commands etc".
-----------------
make these required changes and ask for another review 👍 😄 
HAPPY CODING!!

![programming-happy-fast-gif](https://user-images.githubusercontent.com/64173189/110022042-782f5180-7cf9-11eb-9d33-1c0c143eca02.gif)

2021-03-05 17:49 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi Team! 👋 
You have done a great job implementing the changes requested by the previous TSE! 👍 There are just a few issues that need to be resolved before you can move on: ⬇️ 
****
### **TABLET**

- [x] The layout is not as it should be on the tablet (768px). The first sections (Featured stories, top story, sponsored insight,  my turn, culture and travel, latest news) should be in two columns then it should switch to one column for the remaining sections.
The original page 👇🏾 
![Screen Shot 2021-03-05 at 6 28 02 PM](https://user-images.githubusercontent.com/48804258/110151237-860bd200-7de0-11eb-899f-eeab91331803.png)
![Screen Shot 2021-03-05 at 6 28 13 PM](https://user-images.githubusercontent.com/48804258/110151251-8c9a4980-7de0-11eb-95da-05c57a5d3fcd.png)

Your clone 👇🏾 
![Screen Shot 2021-03-05 at 6 28 27 PM](https://user-images.githubusercontent.com/48804258/110151277-9459ee00-7de0-11eb-990e-b530692964b1.png)
![Screen Shot 2021-03-05 at 6 28 55 PM](https://user-images.githubusercontent.com/48804258/110151342-a5a2fa80-7de0-11eb-80ab-ff5cdc85630c.png)
![Screen Shot 2021-03-05 at 6 29 03 PM](https://user-images.githubusercontent.com/48804258/110151357-ab004500-7de0-11eb-8f67-67a1f30755c1.png)

### **MOBILE**

- [ ] The subscribe button is overlapping with the logo on the mobile screen 👇🏾 
![Screen Shot 2021-03-05 at 6 29 54 PM](https://user-images.githubusercontent.com/48804258/110151442-c8cdaa00-7de0-11eb-9b21-cd61db5ec498.png)

- [x] Featured stories is missing on the mobile screen. It should come after top story. 
- [ ] The debate should come below featured stories, then opinion, sponsored insight, more stories, latest news, my turn, culture & travel, sponsored insight, free signup, then sponsored insight. Please make sure they are in the correct the order.
 
### **GENERAL**
- [ ] Some of your css styles can be done with bootstrap classes. Take a look at your css file again and use this [cheatsheet](https://hackerthemes.com/bootstrap-cheatsheet/) to see what can be done with bootstrap instead. 
****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2021-03-05 17:49 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with the bootstrap class w`-100`

2021-03-05 17:49 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with the bootstrap class `d-none`

2021-03-05 17:49 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with the bootstrap classes `float-left` and `w-100`

2021-03-05 17:49 UTC, BrittanyBlake commented on style.css
> +  font-weight: bold;
- [ ] This can be done with the bootstrap classes `text-decoration-none` and `font-weight-bold`

2021-03-05 17:49 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with the bootstrap classes

2021-03-05 17:49 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with the bootstrap classes `p-0` and `flex-wrap`

2021-03-05 17:49 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with the bootstrap classes `flex-wrap`, `list-unstyled`, and `p-0`

2021-03-05 17:49 UTC, BrittanyBlake commented on style.css
> +  width: 100%;
- [ ] This can be done with the bootstrap classes

2021-03-05 17:49 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with the bootstrap classes `d-block`

2021-03-05 17:49 UTC, BrittanyBlake commented on style.css
> +  padding-left: 0;
- [ ] This can be done with the bootstrap classes `pl-0`

2021-03-05 17:49 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with the bootstrap classes

2021-03-05 17:49 UTC, BrittanyBlake commented on style.css
> +  float: right;
- [ ] This can be done with the bootstrap classes

2021-03-05 17:49 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with the bootstrap classes

2021-03-05 17:49 UTC, BrittanyBlake commented on style.css
> +}
- [ ] This can be done with the bootstrap classes

2021-03-05 17:49 UTC, BrittanyBlake commented on style.css
> +  font-weight: bold;
- [ ] This can be done with the bootstrap classes `text-uppercase` and `font-weight-bold`

2021-03-05 17:49 UTC, BrittanyBlake commented on style.css
> +  align-items: center;
- [ ] This can be done with bootstrap classes

2021-03-05 17:49 UTC, BrittanyBlake commented on style.css
> +  }
- [ ] This can be done with the bootstrap class `d-md-block`

2021-03-05 18:14 UTC, Anvi98 commented on style.css
> +  font-weight: bold;
For this part, we have different li elements with the same class, so we found it would be more interesting to just create a class and assign them in one time this style instead of going and repeating the same class for all li elements

2021-03-05 18:19 UTC, Anvi98 commented on style.css
> +}
Here also, different images have the same property so we found it more interesting to create a personalized variable for all of them and assigning one time a value instead of writing many time on the HTML

2021-03-05 18:20 UTC, Anvi98 commented on style.css
> +  font-weight: bold;
The same explained above

2021-03-05 18:26 UTC, Anvi98 commented on style.css
> +  }
Class removed

2021-03-05 18:27 UTC, Anvi98 commented
I think all is okay now :-)

2021-03-06 00:18 UTC, chubaquelo requested changes
# STATUS: Changes Required 🔴🛠️

![](https://media1.giphy.com/media/l3V0HZY2mToJxWi2s/giphy.gif)

**Hello there! Thanks for your effort in making the required changes. We still just need to fix some issues. It will help you avoid problems with the next milestones. You're almost there! 💪💪**

[REQUIRED CHANGES]

- [x] Each image have a link with <a> tag (you have set CSS class with the cursor: pointer for news images and titles, but it's required to have a < a > tag. You can set the href to # )
- [x] Each title must have a link. Same as the previous point. Use < a > tag, not a cursor: pointer class please.
- [x] Your website layout is not displaying correctly. Please fix that, header must be aligned with the body:

![Screenshot](https://i.imgur.com/LZ5ECsW.jpeg)

- [x] For mobile view: Header has empty space on top and logo is not center aligned. Kindly fix that to keep it as the original.
- [ ] As pointed by the previous TSE, please use bootstrap classes for styles included in bootstrap as:

1. padding: 0
2. margin: 0
3. display: block
4. display: flex
5. color: white
6. font-weight: bold
7. float: right
8. text-transform: uppercase;
9. width: 100%;


**As previous TSE didn't point it out, I will set this as Optional but please take into count for the next milestone:**

[OPTIONAL CHANGES]

- [ ] Please use CSS variables for repeated colors in your stylesheet, so your code is as DRY as possible.



**Please make the required changes and submit another review request when you are ready.**

---

### If you have any question kindly reach me on slack as 'Sergio Obolevich'
Github: [@**chubaquelo**](https://www.github.com/chubaquelo)

### **HAPPY CODING 💻🚀🎉**

2021-03-06 12:33 UTC, Anvi98 commented
For the font-weight property, we preferred to use a personalized class for assigning the font since we have different HTML  element for the same style. Instead of writing the same property for all of them, we just created a class for them.

2021-03-06 12:37 UTC, Anvi98 commented
Hey please our milestone 3 is already approved only remaining this milestone 2:- ). We need an urgent review if possible, please.

2021-03-06 14:21 UTC, smcommits commented on style.css
> +  margin: 0 auto;
This is easily achievable through the bootstrap class `mx-auto`

2021-03-06 14:22 UTC, smcommits commented on style.css
> +  border: none;
This is easily achievable through the bootstrap class `border-0`

2021-03-06 14:30 UTC, smcommits requested changes
# Status: Changes Requested :+1: 
### Hello, team! You have done a great job. The website appears to be fantastic. But, I can see that you have not addressed a significant issue that was pointed out by the previous TSE. 

## Required Changes
#### You still have not implemented the following change
- [x]  **As pointed by the previous TSE, please use bootstrap classes for styles included in bootstrap.** 

This is a very important thing to consider. You are using a lot of CSS selectors for things that are easily achievable through bootstrap classes. This defeats the entire purpose of using a framework. I am referring to some of the selectors below so that you understand the issue better. Previous TSE has also done a great job of evaluating the code related to selectors. Please follow that make maximum use of bootstrap classes. 

I understand that it is exhausting to get change requests again and again, but the issue of not using enough bootstrap classes is a very important one to address. It will serve you well in the future. :+1: :+1: 

# 
Please implement the changes and request another review from your dashboard

###  Please don't hesitate to contact me on [Slack](https://microverse-students.slack.com/team/U017N7LLZ40) if you need assistance or believe I have overlooked something and made an unfair request.

2021-03-06 15:53 UTC, Anvi98 commented on style.css
> +  margin: 0 auto;
Yes We fixed this one

2021-03-06 15:53 UTC, Anvi98 commented on style.css
> +  border: none;
also this one

2021-03-06 15:56 UTC, Anvi98 commented
Yeah, Dear TSE, you are right, but we followed the requirement to use bootstrap properties, also we need to use them in a way we won't repeat too much ourselves if you look at our last commit, we repeated ourselves just because you wanted to see those properties. We really got the importance of using bootstrap properties to thank you very much for all.

2021-03-06 17:07 UTC, enaburekhan requested changes
# Status: Changes requested:full_moon:
**Hi team!
Great job so far on this milestone:clap::clap:. We are almost there. The cloned page has met all the requirements except that we need to follow best css practices:blush:.**

**To improve**

- [x] In the style.css,  color: #000 was reused more than 10 times. This is not a good css practice. Use a class instead. e,g .black { color: #000; } or any other better method. Just make sure you adhere to DRY(don't repeat yourself).

Make the above change and when you are ready, request another review.
Kindly drop your questions :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy coding:blush:
Eric Enaburekhan

2021-03-06 17:26 UTC, Anvi98 commented
Thank you very much, We fixed now this one :-)

2021-03-06 18:34 UTC, bini-i requested changes
# Status: Changes requred :yellow_circle:  
### Hello  team :wave: 

#### Thanks for working on the requirements suggested by previous TSEs but you should work on all requirements for this project to be approved:

- [x] Please work on your header section on mobile screen as it is misaligned as shown below:
> Original
![image](https://user-images.githubusercontent.com/61377322/110217074-32be8000-7ec3-11eb-98fc-5d807ab863a5.png)
> Clone
![image](https://user-images.githubusercontent.com/61377322/110217079-44078c80-7ec3-11eb-99f6-fc7d5b46f1d2.png)

- [x] Kindly use bootstrap classes as much as possible as the aim of the project is to demonstrate using bootstrap skills.
       - use bootstrap classes for properties such as margins, padding, display, float, colors and more as you currently have lots of inside style.css 

#### If you have any question kindly reach me on slack @Binyam Hailemeskel

### HAPPY CODING :computer: :blush: 

> #### Reviewed by Binyam Hailemeskel (TSE)
> GitHub: [@bini-i](https://github.com/bini-i)
> Twitter: [@binyamshewa](https://twitter.com/binyamshewa)
> LinkedIn: [LinkedIn](https://www.linkedin.com/in/binyam-hailemeskel-728048151/)

2021-03-06 19:36 UTC, Spayco approved these changes
# Project Approved

thank you for making the required changes, your project is now approved!

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-03-06 19:51 UTC, closed without merging