Milestone3 - Newsweek
Anvi98/Project-3-Newsweek pull request #7
Opened 2021-03-03 22:31 UTC by Anvi98

In the third and last milestone of the project, we completed the last sections of the website and prepared it for our portfolio.

Main sections ( US; World; Business; Tech & Science; Culture; Sports; Expert forum)

We Created these sections of the website for the 3 screen sizes.

Thank you

2021-03-04 06:21 UTC, bini-i requested changes
# Status: Changes requred :yellow_circle:  
### Hello  team :wave: 

#### Very nice project, you have done really well precisely matching the source page plus you have a great README and commit history but you still can improve your project with the requirements suggested below:
- In the magazine, Editor's pick and main newspaper section, please make sure each title and image has a link and try giving a link to the image and title individually instead of wrapping both of them in a link tag. (refer to inline comments)
- Please make sure the Newsletter section has an input with type **email**
- Subscribe and newsletter section should match the source page on mobile view (image should be stacked on top of title) and fix the overflow
> Original 
![image](https://user-images.githubusercontent.com/61377322/109917984-4ef5cd80-7cc7-11eb-9455-27116ebb9531.png)
> Clone 
![image](https://user-images.githubusercontent.com/61377322/109918069-7b114e80-7cc7-11eb-9ee6-5c26cec630c7.png)

#### You still have requirements to work on from milestone 2
- The layout below header should match the original page as 
* [ ] you should have 2 column layout on medium screen (you currently have 3 column layout)
* [ ] and on mobile screen you should match the following order for the sections
> ![image](https://user-images.githubusercontent.com/61377322/109920009-b1040200-7cca-11eb-88d7-89965049258d.png)

#### If you have any question kindly reach me on slack @Binyam Hailemeskel

### HAPPY CODING :computer: :blush: 

> #### Reviewed by Binyam Hailemeskel (TSE)
> GitHub: [@bini-i](https://github.com/bini-i)
> Twitter: [@binyamshewa](https://twitter.com/binyamshewa)
> LinkedIn: [LinkedIn](https://www.linkedin.com/in/binyam-hailemeskel-728048151/)

2021-03-04 06:21 UTC, bini-i commented on index.html
> +            Israel Security Officials Reveal Top Threats Faced on Four Fronts This Year
Please provide links to the titles of each category (for this and all similar sections below :point_down: )

2021-03-04 06:21 UTC, bini-i commented on index.html
> +            <img
Please provide links for images (here and in all matching sections below)

2021-03-04 06:21 UTC, bini-i commented on index.html
> +                'Tiger King' Zoo Owners Ordered To Hand Over Big Cats to
Please provide links for titles (here and in all matching sections below)

2021-03-04 06:21 UTC, bini-i commented on index.html
> +                  <input type="text" id="email-address" class="form-text" placeholder="Email address">
* [x] Please make sure Newsletter section has an input with type email

2021-03-04 19:55 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [ ] You haven't done any commit after the previous code review, please make the changes asked by them and then ask for another.

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-03-05 15:11 UTC, uche-inyama approved these changes
## Approved

### Hi @Anvi98 :wave: 

Go on with the next task.

### Happy coding :man_technologist: 

#### ``` Uchechukwu Henry Inyama ```

2021-03-06 17:56 UTC, closed without merging